#arrays are similar to list but one diff is 
# you need to have all the valus of same type.(data type)
# for ex.. int ,float only 
# arrays in python they dont have fix size (we can expand )
# they are mutable
# in python arrays are not built in data type
# we have to use numpy library


# arr = [12, 3, 4, 15]
# ans = sum(arr)
# print('Sum of the array is ', ans)
# print(max(arr))

print("hello");print("hi")
print("hello",end=" ");print("hi")





