#29
### (STRING FORMATING)
#### F STRING IN PYTHON ####


# latter = "Hey my name is {} and i am from {}"
# latter = "Hey my name is {0} and i am from {1}"
# contry = "India"
# name="Gangaprasad"
# print(latter.format(name,contry))

#### instade of doing above we use f string

# latter = "Hey my name is {} and i am from {}"
# contry = "India"
# name="Gangaprasad"
# print(f"Hey my name is {name} and i am from {contry}")
#print(f"We use f-strings like this: Hey my name is {{name}} and I am from {{country}}")

# price = 49.09999
# txt = f"For only {price:.3f} dollars!"
# print(txt)
# print(txt.format())
# print(f"{2 * 30}")
# print(type(f"{2 * 30}"))


